# Generated by Django 6.0.4 on 2026-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="contactmessage",
            name="service_interest",
            field=models.CharField(
                choices=[
                    ("Accounting Support", "Accounting Support"),
                    ("Data Analytics", "Data Analytics"),
                    ("Business Solutions", "Business Solutions"),
                    ("General Inquiry", "General Inquiry"),
                ],
                default="General Inquiry",
                max_length=100,
            ),
        ),
    ]
