# Generated by Django 6.0.4 on 2026-04-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_price_product_price_sle_product_price_usd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
