# Generated by Django 6.0.4 on 2026-04-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_product_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="platform_fee_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="platform_fee_percent",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name="order",
            name="seller_earning",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
