# Generated by Django 6.0.4 on 2026-04-24 22:52

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_alter_order_currency_productimage_delete_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_reference",
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="service_interest",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="currency",
            field=models.CharField(default="SLE", max_length=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="Pending", max_length=30),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="payoutrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_sle",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_usd",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
