# Generated by Django 6.0.4 on 2026-04-27 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_alter_category_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
        migrations.RemoveField(
            model_name="payoutrequest",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="product",
            name="available",
        ),
        migrations.RemoveField(
            model_name="product",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_sle",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price_usd",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="created_at",
        ),
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="website.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(default="", upload_to="products/gallery/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="website.product",
            ),
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="PayoutRequest",
        ),
    ]
