# Generated by Django 6.0.4 on 2026-04-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_alter_product_category_remove_productimage_product_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Fair/Damaged", "Fair/Damaged"),
                ],
                default="Good",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
