# Generated by Django 6.0.4 on 2026-04-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_remove_product_image_url_product_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="orange_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
