# Generated by Django 6.0.4 on 2026-04-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_sellerprofile_orange_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="afri_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
