# Generated by Django 6.0.4 on 2026-04-30 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0019_order_remove_product_amount_remove_product_category_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="description",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="image",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[
                    ("Excellent", "Excellent"),
                    ("Good", "Good"),
                    ("Fair/Damaged", "Fair/Damaged"),
                ],
                default="Good",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="Untitled Product", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sellerprofile",
            name="afri_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
