# Generated by Django 6.0.4 on 2026-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_sellerrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="business_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="business_logo",
            field=models.ImageField(blank=True, null=True, upload_to="seller_logos/"),
        ),
    ]
