# Generated by Django 6.0.4 on 2026-05-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_alter_productreview_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
