# Generated by Django 6.0.4 on 2026-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_order_payment_proof"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="condition",
        ),
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="seller",
        ),
        migrations.AddField(
            model_name="product",
            name="deal_label",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_deal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
