# Generated by Django 6.0.4 on 2026-05-20 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0028_product_condition_product_description_product_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="color",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_extra_images/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_images",
                to="website.product",
            ),
        ),
    ]
