# Generated by Django 6.0.4 on 2026-05-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_remove_productimage_color_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
