# Generated by Django 6.0.4 on 2026-05-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0030_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
