# Generated by Django 6.0.4 on 2026-05-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_orderitem_amount_orderitem_color_orderitem_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="payment_proof",
            field=models.ImageField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
    ]
