# Generated by Django 6.0.4 on 2026-05-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0032_product_payment_proof"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_3",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_4",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AddField(
            model_name="product",
            name="image_5",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
