# Generated by Django 6.0.4 on 2026-06-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_product_image_2_product_image_3_product_image_4_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("wrong_item", "Wrong Item"),
                            ("damaged_item", "Damaged Item"),
                            ("delivery", "Delivery Issue"),
                            ("cancel", "Cancel Order"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="website.order",
                    ),
                ),
            ],
        ),
    ]
